# Default values for methode-article-internal-components-mapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  javaOpts:  "-Xms128m -Xmx128m -XX:+UseG1GC -server"
  MAMUrl: "methode-article-mapper:8080"
  MCPMUrl: "methode-content-placeholder-mapper:8080"
  DocStoreUrl: "document-store-api:8080"
  ConcordanceUrl: "public-concordances-api:8080"
  isResilient: "false"
replicaCount: 2
image:
  repository: coco/methode-article-internal-components-mapper
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 256Mi
  limits:
    memory: 512Mi
